name: GS Editor Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Switch to build branch
        run: |
          git fetch origin build || echo "No remote build branch yet"
          git checkout build || git checkout --orphan build

      - name: Copy Build Files
        run: |
          rm -rf *
          cp -r dist/* .
          touch .nojekyll
          rm -rf dist

      - name: Commit and Push Changes
        run: |
          git config user.name "GraphScript Labs Bot"
          git config user.email "bot@graphscriptlabs.dev"
          git add .
          git diff --cached --quiet || git commit -m "Deploy GS Editor"
          git push https://x-access-token:${{ secrets.GRAPHSCRIPT_EDITOR_TOKEN }}@github.com/GraphScript-Labs/graphscript-editor.git HEAD:build
